owner: tomvivi
repo: upptime
sites:
- name: www.google.com
  url: https://www.google.com
  expectedStatusCodes:
  - 200
  - 201
  - 403
  - 404
- name: dpln-guides.com-anomalie-des-etherin-quete-tutorial
  url: https://dpln-guides.com/anomalie-des-etherin/quete/tutorial
  expectedStatusCodes:
  - 200
  - 201
  - 403
  - 404
- name: unity-quetes.blog-fr-mmorpg-actualites-news-anomalie-21701-inscrip.php
  url: https://unity-quetes.blog/fr/mmorpg/actualites/news/anomalie-21701/inscrip.php
  expectedStatusCodes:
  - 200
  - 201
  - 403
  - 404
status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: '**Upptime** is the open-source uptime monitor and status page, powered
    entirely by GitHub.'
  introMessage: "This is a sample status page which uses **real-time** data from our\
    \ [GitHub repository](https://github.com/upptime/upptime). No server required\
    \ \u2014 just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)"
  navbar:
  - title: Status
    href: /
  - title: GitHub
    href: https://github.com/$OWNER/$REPO
